name: 右舷
description: 程序员，与tata507和两只猫一起生活在广州
markdown: redcarpet

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: true
gems: [jekyll-paginate]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
